version: '3'

services:
  localai-ui:
    build: .
    ports:
      - "5000:5000"  # Frontend
      - "5001:5001"  # Backend API
    volumes:
      - ./input:/app/input:ro
      - ./output:/app/output
      - ../shared:/app/shared  # For communication with parent project
      # Docker socket mount - cross-platform compatibility
      - ${DOCKER_SOCKET_PATH:-/var/run/docker.sock}:/var/run/docker.sock:ro
    environment:
      - VITE_API_URL=http://localhost:5001
      - PORT=5001
      - NODE_ENV=production
      # Pass Docker host information to container
      - DOCKER_HOST=${DOCKER_HOST:-unix:///var/run/docker.sock}
      - DOCKER_CERT_PATH=${DOCKER_CERT_PATH:-}
    # Use the host docker group ID for Docker socket access
    # You may need to adjust this based on your system's docker group ID
    # On macOS, this might need to be commented out or use group ID 0
    group_add:
      - "${DOCKER_GROUP_ID:-999}"
    restart: unless-stopped